[package]
name = "raytracer"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
rayon = "1.10.0"
serde = { version = "1.0.216", features = ["derive"] }
serde_with = "3.11.0"
serde_json = "1.0.133"
image = "0.25.5"
chrono = "0.4.39"
